linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - unconvert
    - goconst
    - prealloc
    - nolintlint

linters-settings:
  govet:
    shadow: true
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US

run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
