// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :exec
INSERT INTO attachments (id, message_id, file_name, file_size, mime_type, storage_key, duration_ms, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAttachmentParams struct {
	ID         pgtype.UUID        `json:"id"`
	MessageID  pgtype.UUID        `json:"message_id"`
	FileName   string             `json:"file_name"`
	FileSize   int64              `json:"file_size"`
	MimeType   string             `json:"mime_type"`
	StorageKey string             `json:"storage_key"`
	DurationMs pgtype.Int4        `json:"duration_ms"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.Exec(ctx, createAttachment,
		arg.ID,
		arg.MessageID,
		arg.FileName,
		arg.FileSize,
		arg.MimeType,
		arg.StorageKey,
		arg.DurationMs,
		arg.CreatedAt,
	)
	return err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, message_id, file_name, file_size, mime_type, storage_key, duration_ms, created_at
FROM attachments
WHERE id = $1
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id pgtype.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.StorageKey,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachmentsByMessageID = `-- name: GetAttachmentsByMessageID :many
SELECT id, message_id, file_name, file_size, mime_type, storage_key, duration_ms, created_at
FROM attachments
WHERE message_id = $1
ORDER BY created_at
`

func (q *Queries) GetAttachmentsByMessageID(ctx context.Context, messageID pgtype.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, getAttachmentsByMessageID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.StorageKey,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
