// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChannelSubscriber = `-- name: AddChannelSubscriber :exec
INSERT INTO channel_subscribers (channel_id, user_id, role, subscribed_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (channel_id, user_id) DO NOTHING
`

type AddChannelSubscriberParams struct {
	ChannelID    pgtype.UUID        `json:"channel_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Role         string             `json:"role"`
	SubscribedAt pgtype.Timestamptz `json:"subscribed_at"`
}

func (q *Queries) AddChannelSubscriber(ctx context.Context, arg AddChannelSubscriberParams) error {
	_, err := q.db.Exec(ctx, addChannelSubscriber,
		arg.ChannelID,
		arg.UserID,
		arg.Role,
		arg.SubscribedAt,
	)
	return err
}

const countChannelSubscribers = `-- name: CountChannelSubscribers :one
SELECT COUNT(*) FROM channel_subscribers
WHERE channel_id = $1
`

func (q *Queries) CountChannelSubscribers(ctx context.Context, channelID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelSubscribers, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChannel = `-- name: CreateChannel :exec
INSERT INTO channels (id, slug, name, description, avatar_url, owner_id, is_private, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateChannelParams struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	IsPrivate   bool               `json:"is_private"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) error {
	_, err := q.db.Exec(ctx, createChannel,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.AvatarUrl,
		arg.OwnerID,
		arg.IsPrivate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, slug, name, description, avatar_url, owner_id, is_private, created_at, updated_at
FROM channels
WHERE id = $1
`

func (q *Queries) GetChannelByID(ctx context.Context, id pgtype.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.OwnerID,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelBySlug = `-- name: GetChannelBySlug :one
SELECT id, slug, name, description, avatar_url, owner_id, is_private, created_at, updated_at
FROM channels
WHERE slug = $1
`

func (q *Queries) GetChannelBySlug(ctx context.Context, slug string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelBySlug, slug)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.OwnerID,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelSubscribers = `-- name: GetChannelSubscribers :many
SELECT channel_id, user_id, role, subscribed_at
FROM channel_subscribers
WHERE channel_id = $1
ORDER BY subscribed_at
`

func (q *Queries) GetChannelSubscribers(ctx context.Context, channelID pgtype.UUID) ([]ChannelSubscriber, error) {
	rows, err := q.db.Query(ctx, getChannelSubscribers, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelSubscriber{}
	for rows.Next() {
		var i ChannelSubscriber
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.Role,
			&i.SubscribedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicChannels = `-- name: GetPublicChannels :many
SELECT id, slug, name, description, avatar_url, owner_id, is_private, created_at, updated_at
FROM channels
WHERE is_private = false
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetPublicChannels(ctx context.Context, limit int32) ([]Channel, error) {
	rows, err := q.db.Query(ctx, getPublicChannels, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.AvatarUrl,
			&i.OwnerID,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserChannels = `-- name: GetUserChannels :many
SELECT c.id, c.slug, c.name, c.description, c.avatar_url, c.owner_id, c.is_private, c.created_at, c.updated_at
FROM channels c
JOIN channel_subscribers cs ON cs.channel_id = c.id
WHERE cs.user_id = $1
ORDER BY c.created_at DESC
`

func (q *Queries) GetUserChannels(ctx context.Context, userID pgtype.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, getUserChannels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.AvatarUrl,
			&i.OwnerID,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isChannelSubscriber = `-- name: IsChannelSubscriber :one
SELECT EXISTS(
    SELECT 1 FROM channel_subscribers
    WHERE channel_id = $1 AND user_id = $2
) AS is_subscriber
`

type IsChannelSubscriberParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsChannelSubscriber(ctx context.Context, arg IsChannelSubscriberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChannelSubscriber, arg.ChannelID, arg.UserID)
	var is_subscriber bool
	err := row.Scan(&is_subscriber)
	return is_subscriber, err
}

const removeChannelSubscriber = `-- name: RemoveChannelSubscriber :exec
DELETE FROM channel_subscribers
WHERE channel_id = $1 AND user_id = $2
`

type RemoveChannelSubscriberParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveChannelSubscriber(ctx context.Context, arg RemoveChannelSubscriberParams) error {
	_, err := q.db.Exec(ctx, removeChannelSubscriber, arg.ChannelID, arg.UserID)
	return err
}

const updateChannel = `-- name: UpdateChannel :exec
UPDATE channels
SET name = $2, description = $3, avatar_url = $4, is_private = $5, updated_at = $6
WHERE id = $1
`

type UpdateChannelParams struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	IsPrivate   bool               `json:"is_private"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) error {
	_, err := q.db.Exec(ctx, updateChannel,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.AvatarUrl,
		arg.IsPrivate,
		arg.UpdatedAt,
	)
	return err
}
