// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChatMember = `-- name: AddChatMember :exec
INSERT INTO chat_members (chat_id, user_id, role, joined_at)
VALUES ($1, $2, $3, $4)
`

type AddChatMemberParams struct {
	ChatID   pgtype.UUID        `json:"chat_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) AddChatMember(ctx context.Context, arg AddChatMemberParams) error {
	_, err := q.db.Exec(ctx, addChatMember,
		arg.ChatID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	return err
}

const createChat = `-- name: CreateChat :exec
INSERT INTO chats (id, type, name, avatar_url, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateChatParams struct {
	ID        pgtype.UUID        `json:"id"`
	Type      ChatType           `json:"type"`
	Name      pgtype.Text        `json:"name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) error {
	_, err := q.db.Exec(ctx, createChat,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.AvatarUrl,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createDirectChatLookup = `-- name: CreateDirectChatLookup :exec
INSERT INTO direct_chat_lookup (chat_id, user_a, user_b)
VALUES ($1, $2, $3)
`

type CreateDirectChatLookupParams struct {
	ChatID pgtype.UUID `json:"chat_id"`
	UserA  pgtype.UUID `json:"user_a"`
	UserB  pgtype.UUID `json:"user_b"`
}

func (q *Queries) CreateDirectChatLookup(ctx context.Context, arg CreateDirectChatLookupParams) error {
	_, err := q.db.Exec(ctx, createDirectChatLookup, arg.ChatID, arg.UserA, arg.UserB)
	return err
}

const getChatByID = `-- name: GetChatByID :one
SELECT id, type, name, avatar_url, created_by, created_at, updated_at
FROM chats
WHERE id = $1
`

func (q *Queries) GetChatByID(ctx context.Context, id pgtype.UUID) (Chat, error) {
	row := q.db.QueryRow(ctx, getChatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatMembers = `-- name: GetChatMembers :many
SELECT chat_id, user_id, role, joined_at
FROM chat_members
WHERE chat_id = $1
`

func (q *Queries) GetChatMembers(ctx context.Context, chatID pgtype.UUID) ([]ChatMember, error) {
	rows, err := q.db.Query(ctx, getChatMembers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMember{}
	for rows.Next() {
		var i ChatMember
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirectChat = `-- name: GetDirectChat :one
SELECT chat_id
FROM direct_chat_lookup
WHERE LEAST(user_a, user_b) = LEAST($1::uuid, $2::uuid)
  AND GREATEST(user_a, user_b) = GREATEST($1::uuid, $2::uuid)
`

type GetDirectChatParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
}

func (q *Queries) GetDirectChat(ctx context.Context, arg GetDirectChatParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getDirectChat, arg.Column1, arg.Column2)
	var chat_id pgtype.UUID
	err := row.Scan(&chat_id)
	return chat_id, err
}

const getUserChats = `-- name: GetUserChats :many
SELECT c.id, c.type, c.name, c.avatar_url, c.created_by, c.created_at, c.updated_at
FROM chats c
JOIN chat_members cm ON c.id = cm.chat_id
WHERE cm.user_id = $1
ORDER BY c.updated_at DESC
`

func (q *Queries) GetUserChats(ctx context.Context, userID pgtype.UUID) ([]Chat, error) {
	rows, err := q.db.Query(ctx, getUserChats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chat{}
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.AvatarUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isChatMember = `-- name: IsChatMember :one
SELECT EXISTS(
    SELECT 1 FROM chat_members WHERE chat_id = $1 AND user_id = $2
) AS is_member
`

type IsChatMemberParams struct {
	ChatID pgtype.UUID `json:"chat_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsChatMember(ctx context.Context, arg IsChatMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatMember, arg.ChatID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const removeChatMember = `-- name: RemoveChatMember :exec
DELETE FROM chat_members
WHERE chat_id = $1 AND user_id = $2
`

type RemoveChatMemberParams struct {
	ChatID pgtype.UUID `json:"chat_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveChatMember(ctx context.Context, arg RemoveChatMemberParams) error {
	_, err := q.db.Exec(ctx, removeChatMember, arg.ChatID, arg.UserID)
	return err
}
