// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (id, chat_id, channel_id, sender_id, type, content, reply_to_id, is_edited, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateMessageParams struct {
	ID        pgtype.UUID        `json:"id"`
	ChatID    pgtype.UUID        `json:"chat_id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	SenderID  pgtype.UUID        `json:"sender_id"`
	Type      MessageType        `json:"type"`
	Content   string             `json:"content"`
	ReplyToID pgtype.UUID        `json:"reply_to_id"`
	IsEdited  bool               `json:"is_edited"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage,
		arg.ID,
		arg.ChatID,
		arg.ChannelID,
		arg.SenderID,
		arg.Type,
		arg.Content,
		arg.ReplyToID,
		arg.IsEdited,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const getChatHistory = `-- name: GetChatHistory :many
SELECT id, chat_id, channel_id, sender_id, type, content, reply_to_id, is_edited, created_at, updated_at
FROM messages
WHERE chat_id = $1
  AND (
    $3::timestamptz IS NULL
    OR created_at < $3::timestamptz
    OR (created_at = $3::timestamptz AND id < $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type GetChatHistoryParams struct {
	ChatID          pgtype.UUID        `json:"chat_id"`
	Limit           int32              `json:"limit"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
}

type GetChatHistoryRow struct {
	ID        pgtype.UUID        `json:"id"`
	ChatID    pgtype.UUID        `json:"chat_id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	SenderID  pgtype.UUID        `json:"sender_id"`
	Type      MessageType        `json:"type"`
	Content   string             `json:"content"`
	ReplyToID pgtype.UUID        `json:"reply_to_id"`
	IsEdited  bool               `json:"is_edited"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetChatHistory(ctx context.Context, arg GetChatHistoryParams) ([]GetChatHistoryRow, error) {
	rows, err := q.db.Query(ctx, getChatHistory,
		arg.ChatID,
		arg.Limit,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatHistoryRow{}
	for rows.Next() {
		var i GetChatHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.ChannelID,
			&i.SenderID,
			&i.Type,
			&i.Content,
			&i.ReplyToID,
			&i.IsEdited,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, chat_id, channel_id, sender_id, type, content, reply_to_id, is_edited, created_at, updated_at
FROM messages
WHERE id = $1
`

type GetMessageByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	ChatID    pgtype.UUID        `json:"chat_id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	SenderID  pgtype.UUID        `json:"sender_id"`
	Type      MessageType        `json:"type"`
	Content   string             `json:"content"`
	ReplyToID pgtype.UUID        `json:"reply_to_id"`
	IsEdited  bool               `json:"is_edited"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMessageByID(ctx context.Context, id pgtype.UUID) (GetMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.ChannelID,
		&i.SenderID,
		&i.Type,
		&i.Content,
		&i.ReplyToID,
		&i.IsEdited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchMessages = `-- name: SearchMessages :many
SELECT id, chat_id, channel_id, sender_id, type, content, reply_to_id, is_edited, created_at, updated_at
FROM messages
WHERE chat_id = $1
  AND content_tsv @@ plainto_tsquery('russian', $2)
ORDER BY ts_rank(content_tsv, plainto_tsquery('russian', $2)) DESC
LIMIT $3
`

type SearchMessagesParams struct {
	ChatID         pgtype.UUID `json:"chat_id"`
	PlaintoTsquery string      `json:"plainto_tsquery"`
	Limit          int32       `json:"limit"`
}

type SearchMessagesRow struct {
	ID        pgtype.UUID        `json:"id"`
	ChatID    pgtype.UUID        `json:"chat_id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	SenderID  pgtype.UUID        `json:"sender_id"`
	Type      MessageType        `json:"type"`
	Content   string             `json:"content"`
	ReplyToID pgtype.UUID        `json:"reply_to_id"`
	IsEdited  bool               `json:"is_edited"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchMessages, arg.ChatID, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMessagesRow{}
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.ChannelID,
			&i.SenderID,
			&i.Type,
			&i.Content,
			&i.ReplyToID,
			&i.IsEdited,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE messages
SET content = $2, is_edited = true, updated_at = $3
WHERE id = $1
`

type UpdateMessageParams struct {
	ID        pgtype.UUID        `json:"id"`
	Content   string             `json:"content"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.db.Exec(ctx, updateMessage, arg.ID, arg.Content, arg.UpdatedAt)
	return err
}
