// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChatType string

const (
	ChatTypeDirect ChatType = "direct"
	ChatTypeGroup  ChatType = "group"
)

func (e *ChatType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatType(s)
	case string:
		*e = ChatType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatType: %T", src)
	}
	return nil
}

type NullChatType struct {
	ChatType ChatType `json:"chat_type"`
	Valid    bool     `json:"valid"` // Valid is true if ChatType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatType) Scan(value interface{}) error {
	if value == nil {
		ns.ChatType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatType), nil
}

type MessageType string

const (
	MessageTypeText   MessageType = "text"
	MessageTypeImage  MessageType = "image"
	MessageTypeFile   MessageType = "file"
	MessageTypeVoice  MessageType = "voice"
	MessageTypeSystem MessageType = "system"
)

func (e *MessageType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageType(s)
	case string:
		*e = MessageType(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageType: %T", src)
	}
	return nil
}

type NullMessageType struct {
	MessageType MessageType `json:"message_type"`
	Valid       bool        `json:"valid"` // Valid is true if MessageType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageType) Scan(value interface{}) error {
	if value == nil {
		ns.MessageType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageType), nil
}

type Attachment struct {
	ID         pgtype.UUID        `json:"id"`
	MessageID  pgtype.UUID        `json:"message_id"`
	FileName   string             `json:"file_name"`
	FileSize   int64              `json:"file_size"`
	MimeType   string             `json:"mime_type"`
	StorageKey string             `json:"storage_key"`
	DurationMs pgtype.Int4        `json:"duration_ms"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Channel struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	IsPrivate   bool               `json:"is_private"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ChannelSubscriber struct {
	ChannelID    pgtype.UUID        `json:"channel_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Role         string             `json:"role"`
	SubscribedAt pgtype.Timestamptz `json:"subscribed_at"`
}

type Chat struct {
	ID        pgtype.UUID        `json:"id"`
	Type      ChatType           `json:"type"`
	Name      pgtype.Text        `json:"name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ChatMember struct {
	ChatID   pgtype.UUID        `json:"chat_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type DirectChatLookup struct {
	ChatID pgtype.UUID `json:"chat_id"`
	UserA  pgtype.UUID `json:"user_a"`
	UserB  pgtype.UUID `json:"user_b"`
}

type Message struct {
	ID         pgtype.UUID        `json:"id"`
	ChatID     pgtype.UUID        `json:"chat_id"`
	ChannelID  pgtype.UUID        `json:"channel_id"`
	SenderID   pgtype.UUID        `json:"sender_id"`
	Type       MessageType        `json:"type"`
	Content    string             `json:"content"`
	ReplyToID  pgtype.UUID        `json:"reply_to_id"`
	IsEdited   bool               `json:"is_edited"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ContentTsv interface{}        `json:"content_tsv"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      string             `json:"type"`
	Payload   []byte             `json:"payload"`
	IsRead    bool               `json:"is_read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Reaction struct {
	MessageID pgtype.UUID        `json:"message_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Emoji     string             `json:"emoji"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Bio          string             `json:"bio"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
