// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reactions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReaction = `-- name: AddReaction :exec
INSERT INTO reactions (message_id, user_id, emoji, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (message_id, user_id, emoji) DO NOTHING
`

type AddReactionParams struct {
	MessageID pgtype.UUID        `json:"message_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Emoji     string             `json:"emoji"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) error {
	_, err := q.db.Exec(ctx, addReaction,
		arg.MessageID,
		arg.UserID,
		arg.Emoji,
		arg.CreatedAt,
	)
	return err
}

const getReactionsByMessageID = `-- name: GetReactionsByMessageID :many
SELECT message_id, user_id, emoji, created_at
FROM reactions
WHERE message_id = $1
ORDER BY created_at
`

func (q *Queries) GetReactionsByMessageID(ctx context.Context, messageID pgtype.UUID) ([]Reaction, error) {
	rows, err := q.db.Query(ctx, getReactionsByMessageID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reaction{}
	for rows.Next() {
		var i Reaction
		if err := rows.Scan(
			&i.MessageID,
			&i.UserID,
			&i.Emoji,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :exec
DELETE FROM reactions
WHERE message_id = $1 AND user_id = $2 AND emoji = $3
`

type RemoveReactionParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Emoji     string      `json:"emoji"`
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) error {
	_, err := q.db.Exec(ctx, removeReaction, arg.MessageID, arg.UserID, arg.Emoji)
	return err
}
